name: Deploy Admin Panel

on:
  push:
    branches:
      - main   # main branchக்கு push ஆனதும் deploy ஆகும்

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Admin App
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1   # உங்கள் bucket region

      # Build output (dist/) → S3 bucketக்குள் /admin pathலே deploy ஆகும்
      - name: Deploy to S3 (Admin)
        run: aws s3 sync dist/ s3://sms-frontend-all1/admin --delete

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation \
          --distribution-id E3B7CMHP2QQ05QFH \
          --paths "/admin/*"
