name: Deploy Admin Panel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3️⃣ Detect Admin Panel folder
      - name: Detect admin folder
        id: folder-check
        run: |
          if [ -d "smsreactadminpannel" ]; then
            echo "FOLDER=smsreactadminpannel" >> $GITHUB_ENV
          else
            echo "Admin panel folder not found, using root..."
            ech
