name: Deploy Admin Panel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3. Detect folder & install dependencies
      - name: Install dependencies
        run: |
          # Check if folder exists
          if [ -d "smsreactadminpannel" ]; then
            cd smsreactadminpannel
          else
            echo "Error: smsreactadminpannel folder not found!"
            exit 1
          fi

          # Make sure package.json exists
          if [ ! -f "package.json" ]; then
            echo "Error: package.json not found in smsreactadminpannel!"
            exit 1
          fi

          npm install
          npm run build

      # 4. Deploy to S3
      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-south-1'
        run: |
          aws s3 cp dist/ s3://sms-frontend-all1/admin --recursive --acl public-read
